/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as AuthenticatedChampionshipsChampionshipIdRouteImport } from './routes/_authenticated/championships.$championshipId'
import { Route as AuthenticatedChampionshipsNewRouteImport } from './routes/_authenticated/championships.new'
import { Route as AuthenticatedChampionshipsChampionshipIdIndexRouteImport } from './routes/_authenticated/championships.$championshipId.index'
import { Route as AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteImport } from './routes/_authenticated/championships.$championshipId.events.$eventId'
import { Route as AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRouteImport } from './routes/_authenticated/championships.$championshipId.players.$playerId'
import { Route as AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRouteImport } from './routes/_authenticated/championships.$championshipId.events.$eventId.index'
import { Route as AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRouteImport } from './routes/_authenticated/championships.$championshipId.events.$eventId.draw'
import { Route as AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRouteImport } from './routes/_authenticated/championships.$championshipId.events.$eventId.draw-pots'
import { Route as AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRouteImport } from './routes/_authenticated/championships.$championshipId.events.$eventId.play'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChampionshipsChampionshipIdRoute =
  AuthenticatedChampionshipsChampionshipIdRouteImport.update({
    id: '/championships/$championshipId',
    path: '/championships/$championshipId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChampionshipsNewRoute =
  AuthenticatedChampionshipsNewRouteImport.update({
    id: '/championships/new',
    path: '/championships/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdIndexRoute =
  AuthenticatedChampionshipsChampionshipIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsChampionshipIdRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedChampionshipsChampionshipIdRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute =
  AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRouteImport.update({
    id: '/players/$playerId',
    path: '/players/$playerId',
    getParentRoute: () => AuthenticatedChampionshipsChampionshipIdRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRouteImport.update({
    id: '/draw',
    path: '/draw',
    getParentRoute: () =>
      AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRouteImport.update(
    {
      id: '/draw-pots',
      path: '/draw-pots',
      getParentRoute: () =>
        AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute,
    } as any,
  )
const AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRouteImport.update({
    id: '/play',
    path: '/play',
    getParentRoute: () =>
      AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/championships/$championshipId': typeof AuthenticatedChampionshipsChampionshipIdRouteWithChildren
  '/championships/new': typeof AuthenticatedChampionshipsNewRoute
  '/championships/$championshipId/': typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  '/championships/$championshipId/events/$eventId': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteWithChildren
  '/championships/$championshipId/players/$playerId': typeof AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute
  '/championships/$championshipId/events/$eventId/draw': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute
  '/championships/$championshipId/events/$eventId/draw-pots': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute
  '/championships/$championshipId/events/$eventId/play': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute
  '/championships/$championshipId/events/$eventId/': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/championships/new': typeof AuthenticatedChampionshipsNewRoute
  '/championships/$championshipId': typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  '/championships/$championshipId/players/$playerId': typeof AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute
  '/championships/$championshipId/events/$eventId/draw': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute
  '/championships/$championshipId/events/$eventId/draw-pots': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute
  '/championships/$championshipId/events/$eventId/play': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute
  '/championships/$championshipId/events/$eventId': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/championships/$championshipId': typeof AuthenticatedChampionshipsChampionshipIdRouteWithChildren
  '/_authenticated/championships/new': typeof AuthenticatedChampionshipsNewRoute
  '/_authenticated/championships/$championshipId/': typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  '/_authenticated/championships/$championshipId/events/$eventId': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteWithChildren
  '/_authenticated/championships/$championshipId/players/$playerId': typeof AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute
  '/_authenticated/championships/$championshipId/events/$eventId/draw': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute
  '/_authenticated/championships/$championshipId/events/$eventId/draw-pots': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute
  '/_authenticated/championships/$championshipId/events/$eventId/play': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute
  '/_authenticated/championships/$championshipId/events/$eventId/': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/join/$inviteCode'
    | '/championships/$championshipId'
    | '/championships/new'
    | '/championships/$championshipId/'
    | '/championships/$championshipId/events/$eventId'
    | '/championships/$championshipId/players/$playerId'
    | '/championships/$championshipId/events/$eventId/draw'
    | '/championships/$championshipId/events/$eventId/draw-pots'
    | '/championships/$championshipId/events/$eventId/play'
    | '/championships/$championshipId/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/join/$inviteCode'
    | '/'
    | '/championships/new'
    | '/championships/$championshipId'
    | '/championships/$championshipId/players/$playerId'
    | '/championships/$championshipId/events/$eventId/draw'
    | '/championships/$championshipId/events/$eventId/draw-pots'
    | '/championships/$championshipId/events/$eventId/play'
    | '/championships/$championshipId/events/$eventId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/join/$inviteCode'
    | '/_authenticated/'
    | '/_authenticated/championships/$championshipId'
    | '/_authenticated/championships/new'
    | '/_authenticated/championships/$championshipId/'
    | '/_authenticated/championships/$championshipId/events/$eventId'
    | '/_authenticated/championships/$championshipId/players/$playerId'
    | '/_authenticated/championships/$championshipId/events/$eventId/draw'
    | '/_authenticated/championships/$championshipId/events/$eventId/draw-pots'
    | '/_authenticated/championships/$championshipId/events/$eventId/play'
    | '/_authenticated/championships/$championshipId/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/championships/$championshipId': {
      id: '/_authenticated/championships/$championshipId'
      path: '/championships/$championshipId'
      fullPath: '/championships/$championshipId'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/championships/new': {
      id: '/_authenticated/championships/new'
      path: '/championships/new'
      fullPath: '/championships/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/championships/$championshipId/': {
      id: '/_authenticated/championships/$championshipId/'
      path: '/'
      fullPath: '/championships/$championshipId/'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdRoute
    }
    '/_authenticated/championships/$championshipId/events/$eventId': {
      id: '/_authenticated/championships/$championshipId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/championships/$championshipId/events/$eventId'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdRoute
    }
    '/_authenticated/championships/$championshipId/players/$playerId': {
      id: '/_authenticated/championships/$championshipId/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/championships/$championshipId/players/$playerId'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdRoute
    }
    '/_authenticated/championships/$championshipId/events/$eventId/': {
      id: '/_authenticated/championships/$championshipId/events/$eventId/'
      path: '/'
      fullPath: '/championships/$championshipId/events/$eventId/'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
    }
    '/_authenticated/championships/$championshipId/events/$eventId/draw': {
      id: '/_authenticated/championships/$championshipId/events/$eventId/draw'
      path: '/draw'
      fullPath: '/championships/$championshipId/events/$eventId/draw'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
    }
    '/_authenticated/championships/$championshipId/events/$eventId/draw-pots': {
      id: '/_authenticated/championships/$championshipId/events/$eventId/draw-pots'
      path: '/draw-pots'
      fullPath: '/championships/$championshipId/events/$eventId/draw-pots'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
    }
    '/_authenticated/championships/$championshipId/events/$eventId/play': {
      id: '/_authenticated/championships/$championshipId/events/$eventId/play'
      path: '/play'
      fullPath: '/championships/$championshipId/events/$eventId/play'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
    }
  }
}

interface AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteChildren {
  AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute
  AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute
  AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute
  AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute
}

const AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteChildren: AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteChildren =
  {
    AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute:
      AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawRoute,
    AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute:
      AuthenticatedChampionshipsChampionshipIdEventsEventIdDrawPotsRoute,
    AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute:
      AuthenticatedChampionshipsChampionshipIdEventsEventIdPlayRoute,
    AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute:
      AuthenticatedChampionshipsChampionshipIdEventsEventIdIndexRoute,
  }

const AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteWithChildren =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute._addFileChildren(
    AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteChildren,
  )

interface AuthenticatedChampionshipsChampionshipIdRouteChildren {
  AuthenticatedChampionshipsChampionshipIdIndexRoute: typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteWithChildren
  AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute: typeof AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute
}

const AuthenticatedChampionshipsChampionshipIdRouteChildren: AuthenticatedChampionshipsChampionshipIdRouteChildren =
  {
    AuthenticatedChampionshipsChampionshipIdIndexRoute:
      AuthenticatedChampionshipsChampionshipIdIndexRoute,
    AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute:
      AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteWithChildren,
    AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute:
      AuthenticatedChampionshipsChampionshipIdPlayersPlayerIdRoute,
  }

const AuthenticatedChampionshipsChampionshipIdRouteWithChildren =
  AuthenticatedChampionshipsChampionshipIdRoute._addFileChildren(
    AuthenticatedChampionshipsChampionshipIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChampionshipsChampionshipIdRoute: typeof AuthenticatedChampionshipsChampionshipIdRouteWithChildren
  AuthenticatedChampionshipsNewRoute: typeof AuthenticatedChampionshipsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChampionshipsChampionshipIdRoute:
    AuthenticatedChampionshipsChampionshipIdRouteWithChildren,
  AuthenticatedChampionshipsNewRoute: AuthenticatedChampionshipsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
