/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated/todos'
import { Route as JoinInviteCodeRouteImport } from './routes/join.$inviteCode'
import { Route as AuthenticatedChampionshipsChampionshipIdRouteImport } from './routes/_authenticated/championships.$championshipId'
import { Route as AuthenticatedChampionshipsNewRouteImport } from './routes/_authenticated/championships.new'
import { Route as AuthenticatedChampionshipsChampionshipIdIndexRouteImport } from './routes/_authenticated/championships.$championshipId.index'
import { Route as AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteImport } from './routes/_authenticated/championships.$championshipId.events.$eventId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const JoinInviteCodeRoute = JoinInviteCodeRouteImport.update({
  id: '/join/$inviteCode',
  path: '/join/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChampionshipsChampionshipIdRoute =
  AuthenticatedChampionshipsChampionshipIdRouteImport.update({
    id: '/championships/$championshipId',
    path: '/championships/$championshipId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChampionshipsNewRoute =
  AuthenticatedChampionshipsNewRouteImport.update({
    id: '/championships/new',
    path: '/championships/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdIndexRoute =
  AuthenticatedChampionshipsChampionshipIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedChampionshipsChampionshipIdRoute,
  } as any)
const AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute =
  AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteImport.update({
    id: '/events/$eventId',
    path: '/events/$eventId',
    getParentRoute: () => AuthenticatedChampionshipsChampionshipIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/championships/$championshipId': typeof AuthenticatedChampionshipsChampionshipIdRouteWithChildren
  '/championships/new': typeof AuthenticatedChampionshipsNewRoute
  '/championships/$championshipId/': typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  '/championships/$championshipId/events/$eventId': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/championships/new': typeof AuthenticatedChampionshipsNewRoute
  '/championships/$championshipId': typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  '/championships/$championshipId/events/$eventId': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/join/$inviteCode': typeof JoinInviteCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/championships/$championshipId': typeof AuthenticatedChampionshipsChampionshipIdRouteWithChildren
  '/_authenticated/championships/new': typeof AuthenticatedChampionshipsNewRoute
  '/_authenticated/championships/$championshipId/': typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  '/_authenticated/championships/$championshipId/events/$eventId': typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/todos'
    | '/join/$inviteCode'
    | '/championships/$championshipId'
    | '/championships/new'
    | '/championships/$championshipId/'
    | '/championships/$championshipId/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/todos'
    | '/join/$inviteCode'
    | '/'
    | '/championships/new'
    | '/championships/$championshipId'
    | '/championships/$championshipId/events/$eventId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/todos'
    | '/join/$inviteCode'
    | '/_authenticated/'
    | '/_authenticated/championships/$championshipId'
    | '/_authenticated/championships/new'
    | '/_authenticated/championships/$championshipId/'
    | '/_authenticated/championships/$championshipId/events/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  JoinInviteCodeRoute: typeof JoinInviteCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/join/$inviteCode': {
      id: '/join/$inviteCode'
      path: '/join/$inviteCode'
      fullPath: '/join/$inviteCode'
      preLoaderRoute: typeof JoinInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/championships/$championshipId': {
      id: '/_authenticated/championships/$championshipId'
      path: '/championships/$championshipId'
      fullPath: '/championships/$championshipId'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/championships/new': {
      id: '/_authenticated/championships/new'
      path: '/championships/new'
      fullPath: '/championships/new'
      preLoaderRoute: typeof AuthenticatedChampionshipsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/championships/$championshipId/': {
      id: '/_authenticated/championships/$championshipId/'
      path: '/'
      fullPath: '/championships/$championshipId/'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdIndexRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdRoute
    }
    '/_authenticated/championships/$championshipId/events/$eventId': {
      id: '/_authenticated/championships/$championshipId/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/championships/$championshipId/events/$eventId'
      preLoaderRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRouteImport
      parentRoute: typeof AuthenticatedChampionshipsChampionshipIdRoute
    }
  }
}

interface AuthenticatedChampionshipsChampionshipIdRouteChildren {
  AuthenticatedChampionshipsChampionshipIdIndexRoute: typeof AuthenticatedChampionshipsChampionshipIdIndexRoute
  AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute: typeof AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute
}

const AuthenticatedChampionshipsChampionshipIdRouteChildren: AuthenticatedChampionshipsChampionshipIdRouteChildren =
  {
    AuthenticatedChampionshipsChampionshipIdIndexRoute:
      AuthenticatedChampionshipsChampionshipIdIndexRoute,
    AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute:
      AuthenticatedChampionshipsChampionshipIdEventsEventIdRoute,
  }

const AuthenticatedChampionshipsChampionshipIdRouteWithChildren =
  AuthenticatedChampionshipsChampionshipIdRoute._addFileChildren(
    AuthenticatedChampionshipsChampionshipIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChampionshipsChampionshipIdRoute: typeof AuthenticatedChampionshipsChampionshipIdRouteWithChildren
  AuthenticatedChampionshipsNewRoute: typeof AuthenticatedChampionshipsNewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChampionshipsChampionshipIdRoute:
    AuthenticatedChampionshipsChampionshipIdRouteWithChildren,
  AuthenticatedChampionshipsNewRoute: AuthenticatedChampionshipsNewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  JoinInviteCodeRoute: JoinInviteCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
